select * from Ama t

CREATE TABLE "CRM"."Ama" 
   (  "USERID" VARCHAR2(100), 
  "USERNAME" VARCHAR2(100), 
  "CPWD" VARCHAR2(200), 
  "REALNAME" VARCHAR2(100), 
  "EMAIL" VARCHAR2(200), 
  "MARK" VARCHAR2(200), 
  "USERTYPE" NUMBER, 
  "USERTYPENAME" VARCHAR2(200), 
  "LXR" NVARCHAR2(50), 
  "PHONE" NVARCHAR2(20), 
  "ADDRESS" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CRM" ;
  
    COMMENT ON COLUMN "CRM"."Ama"."USERNAME" IS '用户名';
 
   COMMENT ON COLUMN "CRM"."Ama"."CPWD" IS '密码';
 
   COMMENT ON COLUMN "CRM"."Ama"."REALNAME" IS '真实姓名';
 
   COMMENT ON COLUMN "CRM"."Ama"."EMAIL" IS '邮箱';
 
   COMMENT ON COLUMN "CRM"."Ama"."MARK" IS '标志';
 
   COMMENT ON COLUMN "CRM"."Ama"."USERTYPE" IS '用户类型';
 
   COMMENT ON COLUMN "CRM"."Ama"."USERTYPENAME" IS '用户类型名称';
 
   COMMENT ON COLUMN "CRM"."Ama"."LXR" IS '联系人';
 
   COMMENT ON COLUMN "CRM"."Ama"."PHONE" IS '电话';
 
   COMMENT ON COLUMN "CRM"."Ama"."ADDRESS" IS '地址';